#!/usr/bin/env python3
# Copyright 2026 Matteo Bernacchia <dev@kikijiki.com>
#
# SPDX-License-Identifier: MIT

"""Emit the dense back-stock scenario used by `just demo` and stocking tests.

Usage::

    tools/generate_dense_restock_scenario.py \\
        --out ros_ws/src/restocker_gazebo/config/dense_restock_products.yaml
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import yaml

REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPOSITORY_ROOT / "ros_ws" / "src" / "restocker_gazebo"))

from restocker_gazebo.lane_columns import dense_restock_scenario  # noqa: E402

HEADER = """# Generated by tools/generate_dense_restock_scenario.py. Do not hand-edit.
# Copyright 2026 Matteo Bernacchia <dev@kikijiki.com>
#
# FRONT (+Y): partial columns total 15/24 cans, 13/22 small bottles, and 9/16 large
# bottles. BACK (-Y), independently ordered left-to-right: 7/8 large-bottle grid slots,
# 9/10 can slots, then 9/10 small-bottle slots. The 25 back products match the 25 front
# deficits.
#
# Each back block is two products wide. The 0.15-0.16 m lateral pitch clears the open
# gripper/padded-wrist approach corridor; the 0.085-0.110 m depth pitch leaves a small surface
# gap. The back-right slot in every grid is vacant.
"""


def main() -> int:
    """Write the dense restock scenario document."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=REPOSITORY_ROOT
        / "ros_ws"
        / "src"
        / "restocker_gazebo"
        / "config"
        / "dense_restock_products.yaml",
    )
    arguments = parser.parse_args()

    scenario = dense_restock_scenario()
    document = HEADER + yaml.safe_dump(scenario, sort_keys=False, default_flow_style=False)
    arguments.out.write_text(document)
    print(f"wrote {len(scenario['products'])} products to {arguments.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
