#!/usr/bin/env python3
# Copyright 2026 Matteo Bernacchia <dev@kikijiki.com>
#
# SPDX-License-Identifier: MIT

"""Emit a scenario that stands known product columns in shelf lanes.

Usage::

    tools/generate_lane_column_scenario.py --out scenario.yaml \\
        lane_01=can.standard:12 lane_02=bottle.small.standard:1

A lane not named is left empty. An empty lane and a lane the camera could not see report the
same free depth; the coverage value tells them apart.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import yaml

REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPOSITORY_ROOT / "ros_ws" / "src" / "restocker_gazebo"))

from restocker_gazebo.lane_columns import (  # noqa: E402
    CATALOGUE,
    LaneColumn,
    ground_truth_available_depth_m,
    lane_column_scenario,
)

HEADER = """# Generated by tools/generate_lane_column_scenario.py. Do not hand-edit.
#
# Lanes holding columns of known length, for measuring the wrist camera's lane depletion reading
# against the simulator's own. Every product is static and stands at a computed pose (see
# restocker_gazebo/lane_columns.py).
#
# Expected ground-truth available_depth_m per lane, from the same axis-aligned bound
# lane_evidence.cpp takes:
{expectations}
"""


def _column(argument: str) -> LaneColumn:
    lane, _, rest = argument.partition("=")
    geometry, _, count = rest.partition(":")
    if not lane or geometry not in CATALOGUE or not count.isdigit():
        raise argparse.ArgumentTypeError(
            f"expected lane_XX=<geometry_key>:<count>, got {argument!r}"
        )
    return LaneColumn(lane_id=lane, geometry_key=geometry, count=int(count))


def main() -> int:
    """Write the requested scenario document to a file or to standard output."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("columns", nargs="+", type=_column)
    parser.add_argument("--out", type=Path, default=None)
    arguments = parser.parse_args()

    scenario = lane_column_scenario(arguments.columns)
    expectations = "\n".join(
        f"#   {column.lane_id}: {column.count} x {column.geometry_key} -> "
        f"{ground_truth_available_depth_m(column.geometry_key, column.count):.4f} m"
        for column in arguments.columns
    )
    document = HEADER.format(expectations=expectations) + yaml.safe_dump(
        scenario, sort_keys=False, default_flow_style=False
    )
    if arguments.out is None:
        sys.stdout.write(document)
    else:
        arguments.out.write_text(document)
        print(f"wrote {len(scenario['products'])} products to {arguments.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
