#!/usr/bin/env python3
# Copyright 2026 Matteo Bernacchia <dev@kikijiki.com>
#
# SPDX-License-Identifier: MIT

"""Emit the Card 010 sensor-driven acceptance scenario (three depleted lanes, mixed tray).

Usage::

    tools/generate_sensor_acceptance_scenario.py \\
        --out ros_ws/src/restocker_gazebo/config/sensor_acceptance_products.yaml
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import yaml

REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPOSITORY_ROOT / "ros_ws" / "src" / "restocker_gazebo"))

from restocker_gazebo.lane_columns import sensor_acceptance_scenario  # noqa: E402

HEADER = """# Generated by tools/generate_sensor_acceptance_scenario.py. Do not hand-edit.
# Copyright 2026 Matteo Bernacchia <dev@kikijiki.com>
#
# Card 010 SC-001 acceptance fixture: three depleted lanes start empty (targets 1/1/1 in
# sensor_acceptance_lanes.yaml) and an unordered mixed tray stocks exactly one product per
# class at interleaved x/y poses. One product per class is required for camera identity:
# ObservationIdentityAssigner only identifies a class the object manifest stocks exactly
# one of, and this document is that manifest (object_manifest_path).
"""


def main() -> int:
    """Write the sensor acceptance scenario document."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=Path,
        default=REPOSITORY_ROOT
        / "ros_ws"
        / "src"
        / "restocker_gazebo"
        / "config"
        / "sensor_acceptance_products.yaml",
    )
    arguments = parser.parse_args()

    scenario = sensor_acceptance_scenario()
    document = HEADER + yaml.safe_dump(scenario, sort_keys=False, default_flow_style=False)
    arguments.out.write_text(document)
    print(f"wrote {len(scenario['products'])} products to {arguments.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
